project_id = "DevDogs-Website"

[api]
enabled = true
port = "env(SB_API_PORT)"
schemas = ["public", "graphql_public","storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = "env(SB_DB_PORT)"
shadow_port = "env(SB_DB_SHADOW_PORT)"
major_version = 17

[db.pooler]
enabled = false
port = "env(SB_DB_POOLER_PORT)"
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = true
port = "env(SB_STUDIO_PORT)"
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = "env(SB_INBUCKET_PORT)"

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.avatars]
public = true
file_size_limit = "256KiB"
allowed_mime_types = ["image/webp"]

[storage.buckets.feedback-attachments]
public = false
file_size_limit = "5MiB"
allowed_mime_types = ["image/jpeg","image/png","image/webp","image/gif","application/pdf"]

[auth]
enabled = true
site_url = "env(BASE_URL)"
additional_redirect_urls = ["env(BASE_URL)/api/auth/callback"]
enable_manual_linking = true

# [auth.hook.custom_access_token]
# enabled = true
# uri = "pg-functions://postgres/public/custom_access_token_hook"

[auth.oauth_server]
enabled = true
authorization_url_path = "/oauth/consent"

[auth.external.discord]
enabled = true
client_id = "env(DISCORD_CLIENT_ID)"
secret = "env(DISCORD_CLIENT_SECRET)"

[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_CLIENT_SECRET)"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[auth.external.linkedin_oidc]
enabled = true
client_id = "env(LINKEDIN_CLIENT_ID)"
secret = "env(LINKEDIN_CLIENT_SECRET)"

[analytics]
enabled = false
