allowBuilds:
  argon2: true
  bcrypt: true
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - sharp
  - supabase
  - unrs-resolver
packages:
  - .
  - packages/*
ignoreWorkspaceRootCheck: true