import {
  BookOpen,
  CalendarDots,
  ChatCircle,
  FileText,
  Handshake,
  Hash,
  House,
  Key,
  Lock,
  Scales,
  Scroll,
  Seal,
  SealCheck,
  Shield,
  ShieldWarning,
  Siren,
  User,
  Users,
} from "@phosphor-icons/react/ssr";
import type { ComponentType, SVGAttributes } from "react";

type IconComponent = ComponentType<SVGAttributes<SVGSVGElement>>;

export const iconMap: Record<string, IconComponent> = {
  House,
  Users,
  Calendar: CalendarDots,
  Handshake,
  BookOpen,
  Key,
  KeyRound: Key,
  ScrollText: Scroll,
  BadgeCheck: SealCheck,
  Lock,
  Shield,
  ShieldQuestion: ShieldWarning,
  User,
  Siren,
  FileText,
  Hash,
  Scale: Scales,
  MessageSquare: ChatCircle,
  Seal,
};
