/**
 * Regenerates everything under `src/generated`.
 *
 * Run it by hand (`pnpm --filter @devdogsuga/og generate`) after a brand asset,
 * a font, or the Phosphor version changes; the output is committed. It is not a
 * build step, and deliberately so — it reaches out to Google Fonts, and a
 * network dependency in `turbo build` would make CI fail for reasons that have
 * nothing to do with the commit under test.
 *
 * Everything it writes is *embedded*, base64 in a TypeScript module rather than
 * a file read at render time. The platform renders these templates inside a
 * Cloudflare Worker, where there is no filesystem to read a .ttf out of and
 * where a runtime fetch would put a second network round trip — and a second
 * way to fail — inside every link unfurl. Embedding costs bundle size once and
 * buys a renderer that cannot fail for want of an asset.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type ComponentType, createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as Phosphor from "@phosphor-icons/react/ssr";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "..", "src", "generated");
const BRAND = path.join(
  HERE,
  "..",
  "..",
  "..",
  "apps",
  "platform",
  "public",
  "brand",
);

const BANNER = `// @generated by scripts/generate.ts — do not edit by hand.\n// Run \`pnpm --filter @devdogsuga/og generate\` to refresh.\n`;

/* ------------------------------------------------------------------ fonts */

/**
 * The faces the templates set type in, and nothing else.
 *
 * Three rather than the site's full range, because every one is carried in the
 * Worker bundle: Hanken Grotesk at 400 and 700 covers body copy and its
 * emphasis, and Alan Sans at 800 is the display weight the headings use. Satori
 * picks a face by exact weight and does not synthesise the ones in between, so
 * a template asking for 600 silently lands on 400 — the templates only ask for
 * these three.
 */
const FACES = [
  { family: "Hanken Grotesk", weight: 400 },
  { family: "Hanken Grotesk", weight: 700 },
  { family: "Alan Sans", weight: 800 },
] as const;

async function fonts() {
  const families = [...new Set(FACES.map((f) => f.family))]
    .map((family) => {
      const weights = FACES.filter((f) => f.family === family).map(
        (f) => f.weight,
      );
      return `family=${family.replace(/ /g, "+")}:wght@${weights.join(";")}`;
    })
    .join("&");

  // The stylesheet Google serves is content-negotiated on User-Agent. With a
  // modern one it answers woff2, which Satori cannot parse (it reads ttf, otf
  // and woff); with none it answers plain TrueType. So: send none, and assert
  // on the format rather than trusting that to stay true.
  const css = await fetch(`https://fonts.googleapis.com/css2?${families}`).then(
    (r) => {
      if (!r.ok) throw new Error(`Google Fonts answered ${r.status}`);
      return r.text();
    },
  );

  const faces = [
    ...css.matchAll(
      /font-family: '([^']+)';[\s\S]*?font-weight: (\d+);[\s\S]*?src: url\((\S+?)\) format\('truetype'\)/g,
    ),
  ];

  const found = new Map(faces.map((m) => [`${m[1]}@${m[2]}`, m[3]!]));
  const entries: string[] = [];

  for (const { family, weight } of FACES) {
    const url = found.get(`${family}@${weight}`);
    if (!url)
      throw new Error(`Google Fonts returned no truetype ${family} ${weight}`);

    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url} answered ${response.status}`);
    const buf = Buffer.from(await response.arrayBuffer());
    // "true" and 0x00010000 are the two legal TrueType magic numbers; anything
    // else means the negotiation above drifted back to woff2 and every render
    // would fall through to Satori's own fallback face.
    const magic = buf.readUInt32BE(0);
    if (magic !== 0x00010000 && buf.subarray(0, 4).toString() !== "true") {
      throw new Error(
        `${family} ${weight} is not TrueType (magic ${magic.toString(16)})`,
      );
    }

    console.log(`  ${family} ${weight}: ${(buf.length / 1024).toFixed(1)} KB`);
    entries.push(
      `  {\n    name: ${JSON.stringify(family)},\n    weight: ${weight},\n    style: "normal",\n    data: "${buf.toString("base64")}",\n  },`,
    );
  }

  writeFileSync(
    path.join(OUT, "fonts.ts"),
    `${BANNER}
/** A face as Satori wants it, with the payload still base64. */
export interface EmbeddedFont {
  name: string;
  weight: 400 | 700 | 800;
  style: "normal";
  data: string;
}

export const EMBEDDED_FONTS: EmbeddedFont[] = [
${entries.join("\n")}
];
`,
  );
}

/* ----------------------------------------------------------------- assets */

/** An `<img src>` Satori can draw, plus the aspect ratio to size it by. */
function dataUri(svg: string) {
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
}

function svgAttrs(svg: string) {
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
  if (!viewBox) throw new Error("asset has no viewBox");
  const [, , w, h] = viewBox.split(/\s+/).map(Number) as [
    number,
    number,
    number,
    number,
  ];
  return { width: w, height: h };
}

/**
 * Where each half of the lockup actually is, in the file's own units.
 *
 * `devdogs-logo-dark.svg` has one viewBox around both marks, so cropping to
 * either one means naming its box. These are the rendered ink bounds, measured
 * once at 40x and rounded in — not the artboard, which carries whitespace on
 * every side and would make "set the mascot to 384px" mean 384px of dog *plus*
 * however much padding the export happened to leave.
 *
 * They are constants rather than something this script derives because
 * measuring them needs a rasteriser, and pulling one in to re-learn four
 * numbers that change only when the logo does is a poor trade. The path-count
 * assertion in `splitLockup` is the guard that matters: it fails loudly if the
 * file is re-exported into a different shape, which is the only way these can
 * silently stop being true.
 */
const MASCOT_BOX = [0, 0, 28.15, 30.05] as const;
const WORDMARK_BOX = [37.35, 8.875, 74.05, 16.1] as const;

/**
 * Splits the combined lockup into the two marks the templates place
 * independently.
 *
 * `devdogs-logo-dark.svg` is one file holding both: 52 paths of mascot followed
 * by a single path of "DevDogs" wordmark. Every layout here sizes the two
 * against each other — the wide banner sets the mascot at 384px and the wordmark
 * at 112 — so they cannot come from one image. The split is by path index and
 * asserted on, because a re-export from the design tool that reorders or
 * re-segments the file would otherwise put half a dog in the wordmark slot.
 */
function splitLockup(file: string) {
  const svg = readFileSync(path.join(BRAND, file), "utf8");
  const paths = svg.match(/<path\b[^>]*\/>/g) ?? [];
  if (paths.length !== 53) {
    throw new Error(
      `${file}: expected 53 paths (52 mascot + 1 wordmark), got ${paths.length}`,
    );
  }

  const crop = (
    body: string,
    box: readonly [number, number, number, number],
  ) => ({
    svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box[0]} ${box[1]} ${box[2]} ${box[3]}">${body}</svg>`,
    box: { width: box[2], height: box[3] },
  });

  return {
    mark: crop(paths.slice(0, 52).join(""), MASCOT_BOX),
    wordmark: crop(paths[52]!, WORDMARK_BOX),
  };
}

function assets() {
  const dark = splitLockup("devdogs-logo-dark.svg");
  const light = splitLockup("devdogs-logo.svg");

  const gdgc = readFileSync(
    path.join(BRAND, "gdgc-uga-lockup-dark.svg"),
    "utf8",
  );
  const gdgMark = readFileSync(path.join(BRAND, "gdg-bracket.svg"), "utf8");

  /**
   * The same lockup for a light ground.
   *
   * The checked-in file is the dark-ground variant: "Google Developer Groups"
   * and "UGA" are white, so on a white ground the chevron and the blue "On
   * Campus" float over nothing. Only the neutral ink changes — Google's four
   * chevron colours and the blue belong to the mark and are left alone.
   *
   * `#636d74` is not a guess at a Google grey. It is sampled from the club's
   * own copy of the lockup at
   * `apps/schedule-builder/public/images/GoogleDevLogo.png`, which is what the
   * UGA chapter actually publishes.
   */
  const gdgcLight = gdgc.replace(/fill="(white|#FFFFFF)"/gi, 'fill="#636d74"');

  const decls: string[] = [];
  const add = (
    name: string,
    svg: string,
    box: { width: number; height: number },
    doc: string,
  ) => {
    decls.push(
      `/** ${doc} */\nexport const ${name}: Asset = {\n  src: "${dataUri(svg)}",\n  width: ${box.width},\n  height: ${box.height},\n};`,
    );
  };

  add(
    "MARK",
    dark.mark.svg,
    dark.mark.box,
    "The mascot alone. Full colour, and legible on any ground dark enough to hold the site's own background.",
  );
  add(
    "WORDMARK_ON_DARK",
    dark.wordmark.svg,
    dark.wordmark.box,
    'The "DevDogs" wordmark in white, cropped to its own ink.',
  );
  add(
    "WORDMARK_ON_LIGHT",
    light.wordmark.svg,
    light.wordmark.box,
    "The same wordmark in black, for the light grounds email bodies use.",
  );
  add(
    "GDG_MARK",
    gdgMark,
    svgAttrs(gdgMark),
    "The official Google Developer Groups bracket mark, downloaded unchanged from developers.google.com.",
  );
  add(
    "GDGC_UGA",
    gdgc,
    svgAttrs(gdgc),
    "The GDG on Campus · UGA chapter lockup, for dark grounds. Rebuilt as vector from Google's official chevron and wordmark.",
  );
  add(
    "GDGC_UGA_LIGHT",
    gdgcLight,
    svgAttrs(gdgc),
    "The same chapter lockup with its neutral ink darkened, for light grounds.",
  );

  writeFileSync(
    path.join(OUT, "assets.ts"),
    `${BANNER}
/**
 * A brand mark as an \`<img>\` source.
 *
 * \`width\`/\`height\` are the artwork's own units, carried so a template can set
 * one dimension and derive the other rather than hard-coding an aspect ratio
 * that goes stale when the artwork is re-exported.
 */
export interface Asset {
  src: string;
  width: number;
  height: number;
}

${decls.join("\n\n")}
`,
  );
}

/* ------------------------------------------------------------------ icons */

/**
 * The Phosphor marks the templates use, taken from the same package the app
 * draws its UI with so the two cannot diverge.
 *
 * Bold weight throughout: these sit next to display type at sizes where the
 * regular weight's hairlines disappear, and the site's own visual language is
 * heavy strokes. Rendered through Phosphor's SSR entry and scraped for path
 * data rather than pattern-matched out of its source, which is minified and
 * free to change shape between releases.
 */
const ICONS = {
  Globe: "the website line",
  InstagramLogo: "socials",
  LinkedinLogo: "socials",
  GithubLogo: "socials",
  CalendarDot: "an event's date",
  Clock: "an event's hours",
  MapPin: "where an event is",
  UsersThree: "the community page",
  EnvelopeSimple: "the email signature",
} as const;

function icons() {
  const decls: string[] = [];

  for (const [name, why] of Object.entries(ICONS)) {
    // Phosphor exports each mark twice, bare and `-Icon` suffixed, and which
    // of the two exists has moved between releases. Try the suffixed name the
    // app's `config/icons.ts` imports, then the bare one.
    const exports = Phosphor as Record<
      string,
      ComponentType<{ weight: string }> | undefined
    >;
    const Icon = exports[`${name}Icon`] ?? exports[name];
    if (!Icon) throw new Error(`@phosphor-icons/react/ssr has no ${name}`);

    // `createElement` rather than calling the component: these are wrapped in
    // `forwardRef`, so they are objects React can render and not functions
    // anything can invoke.
    const markup = renderToStaticMarkup(
      createElement(Icon, { weight: "bold" }),
    );
    const paths = [...markup.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]!);
    if (paths.length === 0) throw new Error(`${name} rendered no paths`);

    decls.push(
      `  /** Phosphor \`${name}\`, bold — ${why}. */\n  ${name}: [\n${paths.map((d) => `    ${JSON.stringify(d)},`).join("\n")}\n  ],`,
    );
  }

  writeFileSync(
    path.join(OUT, "icons.ts"),
    `${BANNER}
/**
 * Path data only, on Phosphor's 256-unit grid. The templates wrap these in
 * their own \`<svg>\` so the fill is the caller's to choose — which is the whole
 * reason these are paths here and not \`<img>\` data URIs like the brand marks.
 */
export const ICON_PATHS = {
${decls.join("\n")}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`,
  );
}

/* ------------------------------------------------------------------- main */

mkdirSync(OUT, { recursive: true });
console.log("fonts:");
await fonts();
console.log("assets + icons:");
assets();
icons();
console.log("done");
